{{- if .Values.global.controlsConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: controls-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  controls-config.json: |
{{ .Files.Get "config/controls-config.json" | nindent 4 }}
{{- end }}