{{- if .Values.accuknox.riskassessment.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-risk-assessment-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.global.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    metadata:
      labels:
        app: k8s-risk-assessment-job
    spec:
      template:
        spec:
          initContainers:
            - name: job-init-container
              image: "{{ .Values.kubescape.image.repository }}:{{ .Values.kubescape.image.tag }}"
              args: ["scan", "framework", "allcontrols,clusterscan,mitre,nsa", "--format", "json", "--cache-dir", "/data/kubescape-cache", "--output", "/data/report.json", "--cluster-name=$(CLUSTER_NAME)"]
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.global.clusterName }}
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: accuknox/accuknox-job:latest
              name: artifact-api-container
              command:
                - '/bin/sh'
                - '/script/augment-and-push-results.sh'
              env:
                - name: URL
                  value: {{ .Values.global.url }}
                - name: TENANT_ID
                  value: {{ .Values.global.tenantId | quote }}
                - name: AUTH_TOKEN
                  value: {{ .Values.global.authToken }}
                - name: CLUSTER_NAME
                  value: {{ .Values.global.clusterName }}
                - name: CLUSTER_ID
                  value: {{ .Values.global.clusterId | quote }}
                - name: LABEL_NAME
                  value: {{ .Values.global.label }}
              volumeMounts:
                - mountPath: /data
                  name: datapath
                - mountPath: /script
                  name: scriptpath
          volumes:
            - name: datapath
              emptyDir: {}
            - name: scriptpath
              configMap:
                name: k8s-risk-assessment-job-script-configmap
          restartPolicy: OnFailure
          serviceAccount: k8s-risk-assessment-job-service-account
{{- end }}  